/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sudoku;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JTextField;

/**
 *
 * @author gpala
 */
public class SudokuPanel extends javax.swing.JPanel {
    Sudoku sudoku = new Sudoku("facil");
    
    
    //OBS esta função printa os valores do jogo no paineltabuleiro
    private void atualizarPainel() {
        int[][] matriz = sudoku.getJogo();
        Component[] componentes = PainelTabuleiro.getComponents(); // pega todos os JTextField

        for (int i = 0; i < 9; i++) {
            for (int j = 0; j < 9; j++) {
                int indice = i * 9 + j; // posição no array de componentes
                if (componentes[indice] instanceof JTextField campo) {
                    
                    int valor = matriz[i][j];
                    if (valor == 0){
                        campo.setText("");
                    }else{
                        campo.setText(String.valueOf(matriz[i][j])); 
                    }
                    
                   campo.setEditable(false);               // se for número fixo
                   campo.setBackground(new Color(255, 255, 255)); // branco
                }
            }
        }
    }

    
    public SudokuPanel() {
        
        initComponents();
        atualizarPainel();
        sudoku.printartabuleiro();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelTabuleiro = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        jTextField49 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jTextField51 = new javax.swing.JTextField();
        jTextField52 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jTextField54 = new javax.swing.JTextField();
        jTextField55 = new javax.swing.JTextField();
        jTextField56 = new javax.swing.JTextField();
        jTextField57 = new javax.swing.JTextField();
        jTextField58 = new javax.swing.JTextField();
        jTextField59 = new javax.swing.JTextField();
        jTextField60 = new javax.swing.JTextField();
        jTextField61 = new javax.swing.JTextField();
        jTextField62 = new javax.swing.JTextField();
        jTextField63 = new javax.swing.JTextField();
        jTextField64 = new javax.swing.JTextField();
        jTextField65 = new javax.swing.JTextField();
        jTextField66 = new javax.swing.JTextField();
        jTextField67 = new javax.swing.JTextField();
        jTextField68 = new javax.swing.JTextField();
        jTextField69 = new javax.swing.JTextField();
        jTextField70 = new javax.swing.JTextField();
        jTextField71 = new javax.swing.JTextField();
        jTextField72 = new javax.swing.JTextField();
        jTextField73 = new javax.swing.JTextField();
        jTextField74 = new javax.swing.JTextField();
        jTextField75 = new javax.swing.JTextField();
        jTextField76 = new javax.swing.JTextField();
        jTextField77 = new javax.swing.JTextField();
        jTextField78 = new javax.swing.JTextField();
        jTextField79 = new javax.swing.JTextField();
        jTextField80 = new javax.swing.JTextField();
        jTextField81 = new javax.swing.JTextField();

        PainelTabuleiro.setBackground(new java.awt.Color(0, 0, 0));
        PainelTabuleiro.setLayout(new java.awt.GridLayout(9, 9));

        jTextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField1.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField1);

        jTextField2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField2.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField2);

        jTextField3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField3.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField3);

        jTextField4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField4.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField4);

        jTextField5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField5.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField5);

        jTextField6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField6.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField6);

        jTextField7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField7.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField7);

        jTextField8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField8.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField8);

        jTextField9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField9.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField9);

        jTextField10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField10.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField10);

        jTextField11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField11.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField11);

        jTextField12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField12.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField12);

        jTextField13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField13.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField13);

        jTextField14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField14.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField14);

        jTextField15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField15.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField15);

        jTextField16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField16.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField16);

        jTextField17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField17.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField17);

        jTextField18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField18.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField18);

        jTextField19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField19.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField19);

        jTextField20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField20.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField20);

        jTextField21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField21.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField21);

        jTextField22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField22.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField22);

        jTextField23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField23.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField23);

        jTextField24.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField24.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField24);

        jTextField25.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField25.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField25);

        jTextField26.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField26.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField26);

        jTextField27.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField27.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField27);

        jTextField28.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField28.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField28);

        jTextField29.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField29.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField29);

        jTextField30.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField30.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField30);

        jTextField31.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField31.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField31);

        jTextField32.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField32.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField32);

        jTextField33.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField33.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField33);

        jTextField34.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField34.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField34);

        jTextField35.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField35.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField35);

        jTextField36.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField36.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField36);

        jTextField37.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField37.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField37);

        jTextField38.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField38.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField38);

        jTextField39.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField39.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField39.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField39);

        jTextField40.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField40.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField40);

        jTextField41.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField41.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField41);

        jTextField42.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField42.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField42);

        jTextField43.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField43.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField43);

        jTextField44.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField44.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField44);

        jTextField45.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField45.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField45);

        jTextField46.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField46.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField46);

        jTextField47.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField47.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField47);

        jTextField48.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField48.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField48);

        jTextField49.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField49.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField49.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField49);

        jTextField50.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField50.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField50);

        jTextField51.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField51.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField51);

        jTextField52.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField52.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField52);

        jTextField53.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField53.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField53);

        jTextField54.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField54.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField54);

        jTextField55.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField55.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField55);

        jTextField56.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField56.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField56);

        jTextField57.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField57.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField57.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField57);

        jTextField58.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField58.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField58.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField58);

        jTextField59.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField59.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField59.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField59);

        jTextField60.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField60.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField60.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField60);

        jTextField61.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField61.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField61.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField61);

        jTextField62.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField62.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField62.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField62);

        jTextField63.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField63.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField63.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField63);

        jTextField64.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField64.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField64.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField64);

        jTextField65.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField65.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField65.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField65);

        jTextField66.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField66.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField66.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField66);

        jTextField67.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField67.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField67.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField67);

        jTextField68.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField68.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField68.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField68.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField68);

        jTextField69.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField69.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField69.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField69.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField69);

        jTextField70.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField70.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField70.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField70.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField70);

        jTextField71.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField71.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField71.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField71);

        jTextField72.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField72.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField72.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField72.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField72);

        jTextField73.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField73.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField73.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField73.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField73);

        jTextField74.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField74.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField74.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField74.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField74);

        jTextField75.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField75.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField75.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField75.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField75);

        jTextField76.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField76.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField76.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField76.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField76);

        jTextField77.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField77.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField77.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField77.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField77);

        jTextField78.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField78.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField78.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField78.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField78);

        jTextField79.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField79.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField79.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField79.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField79);

        jTextField80.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField80.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField80.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField80.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField80);

        jTextField81.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField81.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField81.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField81.setPreferredSize(new java.awt.Dimension(40, 40));
        PainelTabuleiro.add(jTextField81);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(PainelTabuleiro, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(PainelTabuleiro, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelTabuleiro;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField56;
    private javax.swing.JTextField jTextField57;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField jTextField59;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField60;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField jTextField62;
    private javax.swing.JTextField jTextField63;
    private javax.swing.JTextField jTextField64;
    private javax.swing.JTextField jTextField65;
    private javax.swing.JTextField jTextField66;
    private javax.swing.JTextField jTextField67;
    private javax.swing.JTextField jTextField68;
    private javax.swing.JTextField jTextField69;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField70;
    private javax.swing.JTextField jTextField71;
    private javax.swing.JTextField jTextField72;
    private javax.swing.JTextField jTextField73;
    private javax.swing.JTextField jTextField74;
    private javax.swing.JTextField jTextField75;
    private javax.swing.JTextField jTextField76;
    private javax.swing.JTextField jTextField77;
    private javax.swing.JTextField jTextField78;
    private javax.swing.JTextField jTextField79;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField80;
    private javax.swing.JTextField jTextField81;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
